/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hotel.alura.v2;
import conexiones.ConnectionFactory;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JComboBox;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Map;
import java.util.Scanner;
import modelos.Reservas;

/**
 *
 * @author Jesus
 */
public class RegistroReservas extends javax.swing.JFrame {

    /**
     * Creates new form RegistroReservas
     */
    private ConnectionFactory connectionFactory;
    private Connection con = null;
    private int tarifaDia = 10000;
    private Map<String,Integer> datos_formas_pagos = null;
    private long cedula;
    private int valor_apagar;
    private Reservas reservas;
    
    public RegistroReservas() {
        initComponents();
        loadFormas(this.forma_pago);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fecha_salida = new com.toedter.calendar.JDateChooser();
        fecha_inicio = new com.toedter.calendar.JDateChooser();
        forma_pago = new javax.swing.JComboBox<>();
        valor_reserva = new javax.swing.JTextField();
        btn_siguiente = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btn_generar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel1.setBackground(new java.awt.Color(0, 102, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reservas-img-3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 500));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 204));
        jLabel2.setText("SISTEMA DE RESERVA.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(java.awt.Color.black);
        jLabel3.setText("FECHA DE INGRESO.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.black);
        jLabel4.setText("FECHA DE SALIDA.");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.black);
        jLabel5.setText("VALOR DE LA RESERVA.");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(java.awt.Color.black);
        jLabel6.setText("FORMA DE PAGO.");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, -1));

        fecha_salida.setBackground(java.awt.Color.white);
        fecha_salida.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(fecha_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 280, 30));

        fecha_inicio.setBackground(java.awt.Color.white);
        fecha_inicio.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 280, 30));

        forma_pago.setBackground(java.awt.Color.white);
        forma_pago.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        forma_pago.setForeground(java.awt.Color.black);
        jPanel1.add(forma_pago, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 280, 30));

        valor_reserva.setBackground(java.awt.Color.white);
        valor_reserva.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valor_reserva.setForeground(java.awt.Color.black);
        valor_reserva.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        valor_reserva.setText("$");
        valor_reserva.setBorder(null);
        valor_reserva.setMargin(new java.awt.Insets(5, 6, 2, 6));
        jPanel1.add(valor_reserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 180, 30));

        btn_siguiente.setBackground(new java.awt.Color(0, 153, 204));
        btn_siguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_siguiente.setForeground(java.awt.Color.white);
        btn_siguiente.setText("SIGUIENTE.");
        btn_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siguienteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 180, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 280, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 280, 10));

        btn_generar.setBackground(new java.awt.Color(0, 153, 204));
        btn_generar.setForeground(java.awt.Color.white);
        btn_generar.setText("GENERAR.");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_generar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 90, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siguienteActionPerformed
        // TODO add your handling code here:
        Scanner lector = null;
        File fl = new File("Datos-usuario.txt");
        if(fl.exists()){
            try {
                lector = new Scanner(fl);
                while (lector.hasNextLine()) {                    
                    String data = lector.nextLine().split(",")[0];
                    cedula = Long.valueOf(data);
                }
                lector.close();
            } catch (FileNotFoundException ex) {
                throw new RuntimeException(ex);
            }
        }
        if(CamposTexto()){
            try {
                // Codigo de ejecucion.
                this.reservas = new Reservas();
                this.reservas.setDni_cliente(cedula);
                this.reservas.setFecha_ingreso( this.fecha_inicio.getDate());
                this.reservas.setFecha_salida( this.fecha_salida.getDate());
                this.reservas.setValor(this.valor_apagar);
                
                this.reservas.setId_forma_pago(
                        this.datos_formas_pagos.get(
                                this.forma_pago.getSelectedItem()
                        )
                );
                this.con = ConnectionFactory.getConnection(
                        "hotel_alura",
                        "root",
                        "Jesus@1999"
                );
                this.connectionFactory.registerReserva(reservas,con);
            } catch (SQLException ex) {
                throw new RuntimeException(ex);
            }
        }
        
    }//GEN-LAST:event_btn_siguienteActionPerformed

    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        // TODO add your handling code here:
        if(this.fecha_inicio.getDate() != null && this.fecha_salida.getDate() != null){
            int diaInicio = this.fecha_inicio.getDate().getDate();
            int diaFin = this.fecha_salida.getDate().getDate();
            String info = "";
            if(diaFin>diaInicio) {
                this.valor_apagar = (diaFin-diaInicio+1)*this.tarifaDia;
                info = "$ "+this.valor_apagar;
            }
            else if(diaFin==diaInicio){
                this.valor_apagar = this.tarifaDia;
                info = "$ "+this.valor_apagar;
            }
            this.valor_reserva.setText(info);
        }
    }//GEN-LAST:event_btn_generarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_generar;
    private javax.swing.JButton btn_siguiente;
    private com.toedter.calendar.JDateChooser fecha_inicio;
    private com.toedter.calendar.JDateChooser fecha_salida;
    private javax.swing.JComboBox<String> forma_pago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField valor_reserva;
    // End of variables declaration//GEN-END:variables

    private void loadFormas(JComboBox<String> forma_pago) {
        try {
            this.con = ConnectionFactory.getConnection(
                    "hotel_alura",
                    "root",
                    "Jesus@1999"
            );
            this.connectionFactory = new ConnectionFactory();
            this.datos_formas_pagos = this.connectionFactory.loadFormas(con);
            
            for(Map.Entry<String,Integer> item: datos_formas_pagos.entrySet()){
                forma_pago.addItem(item.getKey());
            }
            
            
        } catch (SQLException ex) {
            throw new RuntimeException();
        }
    }

    private boolean CamposTexto() {
        boolean validar = true;
        String data = 
                this.fecha_inicio.getDate()+","+
                this.fecha_salida.getDate()+","+
                this.valor_reserva.getText();
        for(String item:data.split(",")){
            if(item == null){
                validar=false;
                break;
            }
        }
        return validar;
    }
}
